apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webste
  namespace: argocd
spec:
  project: website
  source:
    repoURL: https://github.com/Insurdata/argocd-poc.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true