apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: brayest23/argocd-poc:be32c8705fc8532109fc53100df89b28d8ea0286
        ports:
        - containerPort: 80
