name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag brayest23/argocd-poc:$(date +%s)
    - name: Push Image
      run: docekr push brayest23/argocd-poc:$(date +%s)

